import type {NextPage} from "next";
import Head from "next/head";
import NavBar from "../components/LeftNavBar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Stryker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body className="bg-slate-400">
        {/* <NavBar/> */}
        <main>
          <div className="container mx-auto mt-15">
            <NavBar />
          </div>
          <div className="container max-w-4xl mx-auto pt-16 md:pt-32 text-center break-normal">
            <p className="text-white font-extrabold text-3xl md:text-5xl">Brandon Stryker</p>
            <p className="text-xl md:text-2xl text-gray-500">Welcome to my Portfolio</p>
          </div>
        </main>
      </body>

      <footer>
        <div className="container max-w-4xl mx-auto pt-16 md:pt-32 text-center break-normal">
          <p className="text-xl md:text-2xl text-gray-500">Work in progress</p>
        </div>
      </footer>
    </div>
  );
};

export default Home;
